bab/routes/web.php
<?php

Route::get('/', [
    'uses' => 'LangingController@index',
    'as' => 'index',
]);

Route::post('/contact', [
    'uses' => 'LangingController@contactUs',
    'as' => 'contactUs.store',
]);

Route::get('/admin-login', [
    'uses' => 'Admin\AuthController@showLoginForm',
    'as' => 'admin.get.login',
]);

Route::post('/admin-login', [
    'uses' => 'Admin\AuthController@login',
    'as' => 'admin.post.login',
]);

Route::post('/logout', [
    'uses' => 'Admin\AuthController@logout',
    'as' => 'logout',
]);

Route::get('/admin-forget-password', [
    'uses' => 'Admin\AuthController@showForgetPasswordForm',
    'as' => 'admin.get-forget-password',
]);

Route::group(['middleware' => 'admin', 'prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Route::get('/', [
        'uses' => 'HomeController@dashboard',
        'as' => 'dashboard',
    ]);

    Route::get('/statistics', [
        'uses' => 'HomeController@statistics',
        'as' => 'dashboard-statistics',
    ]);

    Route::resource('admins', 'AdminController', ['except' => ['show', 'destroy']]);

    Route::resource('users', 'UserController', ['except' => ['show','destroy']]);

    Route::resource('cities', 'CitiesController');
    
    Route::resource('regions', 'RegionsController');

    Route::resource('sections', 'SectionsController');

    Route::resource('sub-sections', 'SubsectionController');

    Route::resource('items', 'ItemController', ['except' => ['destroy']]);

    Route::resource('advs', 'AdvsController', ['except' => ['destroy']]);

    Route::resource('about', 'AboutController', ['only' => ['create', 'store']]);

    Route::resource('contactUs', 'ContactUsController', ['only' => ['index', 'show']]);

    Route::get('/change-password', [
        'uses' => 'AdminController@editPassword',
        'as' => 'admins.editPassword',
        ]);

    Route::post('/change-password', [
        'uses' => 'AdminController@changePassword',
        'as' => 'admins.changePassword',
        ]);

    Route::get('/edit-profile', [
        'uses' => 'AdminController@editProfile',
        'as' => 'admins.editProfile',
        ]);

    Route::post('/edit-profile', [
        'uses' => 'AdminController@updateProfile',
        'as' => 'admins.updateProfile',
        ]);

    Route::get('settings/edit', [
        'uses' => 'SettingController@edit',
        'as' => 'settings.edit',
        ]);

    Route::patch('settings/edit', [
        'uses' => 'SettingController@update',
        'as' => 'settings.update',
        ]);

    Route::get('/notifications/{type}', [
        'uses' => 'NotificationController@create',
        'as' => 'notifications.create',
    ]);

    Route::post('/notifications/{type}', [
        'uses' => 'NotificationController@store',
        'as' => 'notifications.store',
    ]);

    Route::post('/users-change-status', [
        'uses' => 'UserController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post('/items-change-status', [
        'uses' => 'ItemController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post( '/cities/change-regions', [
        'uses' => 'CitiesController@changeRegions',
        'as'   => 'cities.changeRegions'
    ] );

    Route::post( '/sections/change-subsections', [
        'uses' => 'ItemController@changeSubsections',
        'as'   => 'sections.changeSubsections'
    ] );

    Route::post('/users-change-account-status', [
        'uses' => 'UserController@changeAccountStatus',
        'as' => 'changeAccountStatus',
    ]);

    Route::get('/users/{user}', [
        'uses' => 'UserController@show',
        'as' => 'users.show',
    ]);

    Route::post('/users/destroy', [
        'uses' => 'UserController@destroy',
        'as' => 'users.destroy',
    ]);

    Route::get('/section-subsections/{section}', [
        'uses' => 'SectionsController@subSections',
        'as' => 'sections.subsections',
    ]);

    Route::post('/contactUs/destroy', [
        'uses' => 'ContactUsController@destroy',
        'as' => 'contactUs.destroy',
    ]);

    Route::post('/contactUs/reply', [
        'uses' => 'ContactUsController@replyMessage',
        'as' => 'contactUs.reply',
    ]);

    Route::post('/cities/destroy', [
        'uses' => 'CitiesController@destroy',
        'as' => 'cities.destroy',
    ]);

    Route::post('/regions/destroy', [
        'uses' => 'regionsController@destroy',
        'as' => 'regions.destroy',
    ]);

    Route::post('/sections/destroy', [
        'uses' => 'sectionsController@destroy',
        'as' => 'sections.destroy',
    ]);

    Route::post('/sub-sections/destroy', [
        'uses' => 'SubsectionsController@destroy',
        'as' => 'subsections.destroy',
    ]);

    Route::post('/items/destroy', [
        'uses' => 'ItemController@destroy',
        'as' => 'items.destroy',
    ]);

    Route::post('/advs/destroy', [
        'uses' => 'AdvsController@destroy',
        'as' => 'advs.destroy',
    ]);

});

bab/app/Section.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Traits\Translatable;

class Section extends Model
{
    use Translatable;
    
    protected $fillable = [
        'name', 'photo',
    ];

    public function SubSections()
    {
        return $this->hasMany(SubSection::class);
    }
}

bab/app/Http/Controllers/Admin/SectionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Section;
use App\SubSection;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class sectionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Section::get();

        return view('admin.sections.index', compact('data'));
    }

    public function subSections(Section $section)
    {
        $data = SubSection::where('section_id', $section->id)->get();

        return view('admin.sections.subs', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.sections.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'         => 'required|max:191',
            'name_en'      => 'required|max:191',
            'photo'        => 'required|mimes:jpg,jpeg,png,tiff',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails())
            return redirect()->route('sections.create')->withErrors($validator)->withInput();


        $imgName = UploadImage($request->photo, 'section', 'sections');

        $created = Section::create([
            'name' => $request->name ,
            'photo' => $imgName , //image
        ]);
        $created->createTranslations([
            'name' => $request->get('name_en'),
        ]);

        $created['imagePath'] = imgPath('sections');

        return $created ?
            redirect()->route('sections.create')->with('success', trans('admin.addOk')) :
            redirect()->route('sections.create')->with('warning', trans('admin.addNo'));
    }

    public function show(Section $section)
    {
        return view('admin.sections.show', compact('section'));
    }

    public function edit(Section $section)
    {
        return view('admin.sections.edit', compact('section'));
    }


    public function update(Request $request, Section $section)
    {
        $rules = [
            'name'    => 'required|max:191',
            'name_en' => 'required|max:191',
            'image'   => 'mimes:jpg,jpeg,png,tiff',
        ];

        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails())
        return redirect()->back()->withErrors($validator)->withInput();

        if ( isset($request->image) && $request->image ) {

            $request['photo'] = UploadImage($request->file('image'), 'section', 'sections');

            @unlink(public_path('\uploads\sections') . $section->photo);
        }

        $updated = $section->update($request->all());
        
        $section->updateTranslations([
            'name' => $request->get('name_en'),
        ]);
        return $updated ?
            redirect()->route('sections.index')->with('success', trans('messages.updateTrue')) :
            redirect()->back()->with('warning', trans('messages.updateFalse'));
    }

    public function destroy(Request $request)
    {
        
        $section = Section::where('id', $request->id)->delete();

        $url = route('sections.index');

        return $section
            ? json_encode(['code' => '1', 'url' => $url])
            : json_encode(['code' => '0', 'message' => 'نأسف لحدوث هذا الخطأ, برجاء المحاولة لاحقًا']);
                
    }

}

bab/app/Http/Controllers/Api/SectionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Section;
use App\SubSection;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class SectionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (config('app.locale') === 'en') {
            $data = Section::with('translations')
                                ->get(['id', 'name','photo'])
                                ->map(function ($section) {
                                    return [
                    'id' => $section->id,
                    'name' => $section->translate('en')->name,
                    'photo' => $section->photo,
                ];
                                });

            return ApiController::respondWithSuccess($data);
        } else {
            $data = Section::select('id', 'name', 'photo')->get();

            return ApiController::respondWithSuccess($data);
        }
    
    }

    public function search(Request $request)
    {
        $rules = [
            'section_id' => 'required|exists:sections,id',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return ApiController::respondWithError(validateRules($validator->errors(), $rules));
        }

        if (config('app.locale') === 'en') {
            $data = SubSection::where('section_id', $request->section_id)->with('translations')
                                ->get(['id', 'name','photo'])
                                ->map(function ($sub) {
                                    return [
                    'id'    => $sub->id,
                    'name'  => $sub->translate('en')->name,
                    'photo' => $sub->photo,
                ];
                                });

            return ApiController::respondWithSuccess($data);
        } else {
            $data = SubSection::select('id', 'name','photo')->where('section_id', $request->section_id)->get();
        }

        return $data
            ?response()->json(['responseCode' => 1, 'subCode' => 200, 'data'=> $data])
            :response()->json(['responseCode' => 0, 'subCode' => 404]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Section $section)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Section  $section
     * @return \Illuminate\Http\Response
     */
    public function destroy(Section $section)
    {
        //
    }
}

bab/resources/views/admin/sections/create.blade.php
@extends('admin.layouts.master')

@section('title')
    إضافة قسم رئيسى
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-fileinput.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('sections.index') }}">الأقسام الرئيسية </a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>إضافة قسم رئيسى </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> الأقسام الرئيسية
        <small>إضافة قسم رئيسى جديد</small>
    </h1>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-8">
        <div class="portlet light bordered">
            <div class="portlet-body form">
                {!! Form::open([ 'url' => route('sections.store'), 'class' => 'form-horizontal','files'=>true ]) !!}

                    <div class="form-group">
                        <label for="name" class="col-lg-3 control-label"> اسم القسم بالعربية </label>
                        <div class="col-lg-9">
                            <input type="text" id="name" name="name" class="form-control " placeholder="اسم القسم بالعربية" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name_en" class="col-lg-3 control-label"> اسم القسم بالانجليزية </label>
                        <div class="col-lg-9">
                            <input type="text" id="name_en" name="name_en"  class="form-control " placeholder="اسم القسم بالانجليزية" required>
                        </div>
                    </div>

                    <div class="form-group ">
                        <label class="control-label col-lg-3">صورة القسم </label>
                        <div class="col-lg-9">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 330px; height: 150px;"> </div>
                                <div>
                                    <span class="btn red btn-outline btn-file">
                                        <span class="fileinput-new"> اختر صورة </span>
                                        <span class="fileinput-exists"> تغيير </span>
                                        <input type="file" name="photo" accept="image/*" required>
                                    </span>
                                    <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> حذف </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-lg-2 col-lg-offset-10">
                                <button type="submit" class="btn green btn-block">حفظ</button>
                            </div>
                        </div>
                    </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/components-select2.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap-fileinput.js') }}"></script>
@endsection

bab/resources/views/admin/sections/edit.blade.php
@extends('admin.layouts.master')

@section('title')
    تعديل القسم
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-fileinput.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('sections.index') }}">الأقسام الرئيسية</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>تعديل قسم رئيسى </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> الأقسام الرئيسية
        <small>تعديل قسم رئيسى </small>
    </h1>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-8">
        <div class="portlet light bordered">
            <div class="portlet-body form">
                {!! Form::model($section, ['method' => 'PATCH', 'files' => 'true' ,'url' => route('sections.update', $section->id),'class' => 'form-horizontal']) !!}
                    <div class="form-group">
                        <label for="name" class="col-lg-3 control-label"> اسم القسم بالعربية </label>
                        <div class="col-lg-9">
                            <input type="text" id="name" name="name" value="{{$section->name}}" class="form-control " placeholder="اسم القسم بالعربية" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name" class="col-lg-3 control-label"> اسم القسم بالانجليزية </label>
                        <div class="col-lg-9">
                            {!! Form::text('name_en', isset($section) ? $section->translate('en')->name : null, ['class' => 'form-control', 'required']) !!}
                        </div>
                    </div>

                    <div class="form-group ">
                        <label class="control-label col-lg-3">صورة القسم</label>
                        <div class="col-lg-9">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                @if( $section->photo )
                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 330px; height: 150px;">
                                        <img src="{{ URL::asset('public/uploads/sections/'.$section->photo) }}">
                                    </div>
                                @endif
                                <div>
                                    <span class="btn red btn-outline btn-file">
                                        <span class="fileinput-new"> تغيير الصورة </span>
                                        <span class="fileinput-exists"> تغيير </span>
                                        <input type="file" name="image" accept="image/*">
                                    </span>
                                    <a href="javascript:;" class="btn red fileinput-exists" data-dismiss="fileinput"> حذف </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-lg-2 col-lg-offset-10">
                                <button type="submit" class="btn green btn-block">حفظ</button>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/components-select2.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap-fileinput.js') }}"></script>
@endsection

bab/resources/views/admin/sections/subs.blade.php
@extends('admin.layouts.master')

@section('title')
    الأقسام الفرعية
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/datatables.bootstrap-rtl.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/sweetalert.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('sub-sections.index') }}">الأقسام الفرعية</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>عرض الأقسام الفرعية </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> عرض الأقسام الفرعية
        <small>عرض الأقسام الفرعية  </small>
    </h1>
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="btn-group">
                                    
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="btn-group pull-right">
                                    <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown" aria-expanded="false">أدوات
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="javascript:;">
                                                <i class="fa fa-print"></i> طباعة
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                        <thead>
                        <tr>
                            <th>
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                    <span></span>
                                </label>
                            </th>
                            <th> الصورة </th>
                            <th> اسم  القسم الفرعى بالعربية   </th>
                            <th> اسم  القسم الفرعى بالإنجليزية  </th>
                            <th> اسم القسم الرئيسى  </th>
                            <th> العمليات </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach( $data as $value )
                            <tr class="odd gradeX">
                                <td>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input type="checkbox" class="checkboxes" value="1" />
                                        <span></span>
                                    </label>
                                </td>
                                <td> <img class="table_img img-preview img-responsive" src="{{ URL::asset('public/uploads/subsections/'.$value->photo) }}"></td>
                                <td> {{ $value->name }} </td>
                                <td> {{ $value->translate('en')->name }} </td>
                                <td> {{ $value->section->name }} </td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> العمليات
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-left" role="menu">
                                            <li>
                                                <a href="{{ route('sub-sections.edit', $value->id) }}">
                                                    <i class="icon-pencil"></i> تعديل
                                                </a>
                                            </li>
                                            <li>
                                                <a class="delete_data" data="{{ $value->id }}" data_name="{{ $value->name }}">
                                                    <i class="fa fa-times"></i> حذف
                                                </a>
                                            </li>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/datatable.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/datatables.bootstrap.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/table-datatables-managed.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/sweetalert.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/ui-sweetalert.min.js') }}"></script>

    <script>
        $(document).ready(function() {

            var CSRF_TOKEN = $('meta[name="X-CSRF-TOKEN"]').attr('content');

            $('body').on('click', '.delete_data', function() {

                var id = $(this).attr('data');
                var swal_text = 'المدينة ' + $(this).attr('data_name');
                var swal_title = 'هل أنت متأكد من الحذف ؟';

                swal({
                    title: swal_title,
                    text: swal_text,
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-warning",
                    confirmButtonText: "تأكيد",
                    cancelButtonText: "إغلاق"
                }, function() {

                    $.ajax({
                        url: "{{ url('/') }}" + "/dashboard/sub-sections/destroy" ,
                        type: "POST",
                        data: {_token: CSRF_TOKEN, 'id' : id},
                    })
                        .done(function(reseived_data) {
                            var parsed_data = $.parseJSON(reseived_data);

                            if(parsed_data.code === '1'){
                                swal({
                                    type: 'success',
                                    title: 'تم الحذف بنجاح',
                                    confirmButtonClass: 'btn-success'
                                }, function() {
                                    window.location.href = parsed_data.url;
                                });
                            }
                            else{
                                swal(
                                    "عملية خاطئة",
                                    parsed_data.message ,
                                    "error"
                                );
                            }
                        });
                });
            });
        });
    </script>
@endsection