bab/routes/web.php
<?php

Route::get('/', [
    'uses' => 'LangingController@index',
    'as' => 'index',
]);

Route::post('/contact', [
    'uses' => 'LangingController@contactUs',
    'as' => 'contactUs.store',
]);

Route::get('/admin-login', [
    'uses' => 'Admin\AuthController@showLoginForm',
    'as' => 'admin.get.login',
]);

Route::post('/admin-login', [
    'uses' => 'Admin\AuthController@login',
    'as' => 'admin.post.login',
]);

Route::post('/logout', [
    'uses' => 'Admin\AuthController@logout',
    'as' => 'logout',
]);

Route::get('/admin-forget-password', [
    'uses' => 'Admin\AuthController@showForgetPasswordForm',
    'as' => 'admin.get-forget-password',
]);

Route::group(['middleware' => 'admin', 'prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Route::get('/', [
        'uses' => 'HomeController@dashboard',
        'as' => 'dashboard',
    ]);

    Route::get('/statistics', [
        'uses' => 'HomeController@statistics',
        'as' => 'dashboard-statistics',
    ]);

    Route::resource('admins', 'AdminController', ['except' => ['show', 'destroy']]);

    Route::resource('users', 'UserController', ['except' => ['show','destroy']]);

    Route::resource('cities', 'CitiesController');
    
    Route::resource('regions', 'RegionsController');

    Route::resource('sections', 'SectionsController');

    Route::resource('sub-sections', 'SubsectionController');

    Route::resource('items', 'ItemController', ['except' => ['destroy']]);

    Route::resource('advs', 'AdvsController', ['except' => ['destroy']]);

    Route::resource('about', 'AboutController', ['only' => ['create', 'store']]);

    Route::resource('contactUs', 'ContactUsController', ['only' => ['index', 'show']]);

    Route::get('/change-password', [
        'uses' => 'AdminController@editPassword',
        'as' => 'admins.editPassword',
        ]);

    Route::post('/change-password', [
        'uses' => 'AdminController@changePassword',
        'as' => 'admins.changePassword',
        ]);

    Route::get('/edit-profile', [
        'uses' => 'AdminController@editProfile',
        'as' => 'admins.editProfile',
        ]);

    Route::post('/edit-profile', [
        'uses' => 'AdminController@updateProfile',
        'as' => 'admins.updateProfile',
        ]);

    Route::get('settings/edit', [
        'uses' => 'SettingController@edit',
        'as' => 'settings.edit',
        ]);

    Route::patch('settings/edit', [
        'uses' => 'SettingController@update',
        'as' => 'settings.update',
        ]);

    Route::get('/notifications/{type}', [
        'uses' => 'NotificationController@create',
        'as' => 'notifications.create',
    ]);

    Route::post('/notifications/{type}', [
        'uses' => 'NotificationController@store',
        'as' => 'notifications.store',
    ]);

    Route::post('/users-change-status', [
        'uses' => 'UserController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post('/items-change-status', [
        'uses' => 'ItemController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post( '/cities/change-regions', [
        'uses' => 'CitiesController@changeRegions',
        'as'   => 'cities.changeRegions'
    ] );

    Route::post( '/sections/change-subsections', [
        'uses' => 'ItemController@changeSubsections',
        'as'   => 'sections.changeSubsections'
    ] );

    Route::post('/users-change-account-status', [
        'uses' => 'UserController@changeAccountStatus',
        'as' => 'changeAccountStatus',
    ]);

    Route::get('/users/{user}', [
        'uses' => 'UserController@show',
        'as' => 'users.show',
    ]);

    Route::post('/users/destroy', [
        'uses' => 'UserController@destroy',
        'as' => 'users.destroy',
    ]);

    Route::get('/section-subsections/{section}', [
        'uses' => 'SectionsController@subSections',
        'as' => 'sections.subsections',
    ]);

    Route::post('/contactUs/destroy', [
        'uses' => 'ContactUsController@destroy',
        'as' => 'contactUs.destroy',
    ]);

    Route::post('/contactUs/reply', [
        'uses' => 'ContactUsController@replyMessage',
        'as' => 'contactUs.reply',
    ]);

    Route::post('/cities/destroy', [
        'uses' => 'CitiesController@destroy',
        'as' => 'cities.destroy',
    ]);

    Route::post('/regions/destroy', [
        'uses' => 'regionsController@destroy',
        'as' => 'regions.destroy',
    ]);

    Route::post('/sections/destroy', [
        'uses' => 'sectionsController@destroy',
        'as' => 'sections.destroy',
    ]);

    Route::post('/sub-sections/destroy', [
        'uses' => 'SubsectionsController@destroy',
        'as' => 'subsections.destroy',
    ]);

    Route::post('/items/destroy', [
        'uses' => 'ItemController@destroy',
        'as' => 'items.destroy',
    ]);

    Route::post('/advs/destroy', [
        'uses' => 'AdvsController@destroy',
        'as' => 'advs.destroy',
    ]);

});

bab/resources/views/admin/layouts/alerts.blade.php
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
            {{ $error }}
        </div>
    @endforeach
@endif


@if(Session::has('success'))
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {{ Session::get('success') }}
    </div>
@endif

@if(Session::has('warning'))
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {{ Session::get('warning') }}
    </div>
@endif

@if(Session::has('danger'))
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
        {{ Session::get('danger') }}
    </div>
@endif

bab/resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
 <html lang="en" class="ie8 no-js">
 <html lang="en" class="ie9 no-js">

<html lang="{{ app()->getLocale() }}" dir="rtl">

<head>
    <meta charset="utf-8" />
    <meta name="X-CSRF-TOKEN" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <link href='https://fonts.googleapis.com/earlyaccess/droidarabickufi.css' rel='stylesheet' type='text/css'/>

    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/font-awesome/css/font-awesome.min.css') }}" />
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/simple-line-icons/simple-line-icons.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-rtl.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-switch-rtl.min.css') }}"/>

    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/components-rounded-rtl.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/plugins-rtl.min.css') }}"/>

    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/layout-rtl.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/darkblue-rtl.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/custom-rtl.min.css') }}"/>

    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/login-rtl.min.css') }}"/>
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/custom.css') }}"/>

    <style>
       /* Set the size of the div element that contains the map */
      #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
    </style>

    @yield('styles')

   {!! Charts::assets() !!} 

    <link rel="shortcut icon" href="favicon.ico" />
</head>

<body class="page-header-fixed page-footer-fixed page-sidebar-closed-hide-logo page-content-white">
    <div class="page-wrapper">
        <!-- BEGIN HEADER -->

        @include('admin.layouts.header')

        <div class="clearfix"> </div>
      
        
        <div class="page-container">
           

            @include('admin.layouts.sidebar')

            <div class="page-content-wrapper">
                <div class="page-content">

                    @yield('page_header')

                    @include('admin.layouts.alerts')

                    @yield('content')

                </div>
            </div>

        </div>
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner"> {{ date('Y') }} &copy; تطوير بواسطة
                <a target="_blank" href="https://brand4it.com"> شركة براند. </a>
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.js"></script>
    <script src="{{ URL::asset('public/admin/js/respond.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/excanvas.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/ie8.fix.min.js') }}"></script>

    <!-- BEGIN CORE PLUGINS -->
    <script src="{{ URL::asset('public/admin/js/jquery.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/js.cookie.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/jquery.blockui.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap-switch.min.js') }}"></script>
    <!-- END CORE PLUGINS -->

    <!-- BEGIN THEME GLOBAL SCRIPTS -->
    <script src="{{ URL::asset('public/admin/js/app.min.js') }}"></script>
    <!-- END THEME GLOBAL SCRIPTS -->

    <!-- BEGIN THEME LAYOUT SCRIPTS -->
    <script src="{{ URL::asset('public/admin/js/layout.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/demo.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/quick-sidebar.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/quick-nav.min.js') }}"></script>

    <!-- END THEME LAYOUT SCRIPTS -->
    <script>
        $(document).ready(function()
        {
            $('#clickmewow').click(function()
            {
                $('#radio1003').attr('checked', 'checked');
            });
        })
    </script>
    @yield('scripts')

</body>

</html>

bab/resources/views/admin/layouts/sidebar.blade.php
<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <li class="nav-item">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">{{ trans('admin.dashboardTitle') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('dashboard') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.statistics') }}</span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('dashboard-statistics') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.statisticsCharts') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ strpos(URL::current(), 'settings') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-settings"></i>
                    <span class="title">{{ trans('admin.sideSettingsTitle') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('settings.edit') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.settings') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
             
            <li class="nav-item {{ strpos(URL::current(), 'admins') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-users"></i>
                    <span class="title">{{ trans('admin.adminsIndex') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('admins.index') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.adminsShow') }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route('admins.create') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.adminsAdd') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item {{ strpos(URL::current(), 'users') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-users"></i>
                    <span class="title"> العملاء </span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('users.index') }}" class="nav-link ">
                            <span class="title">عرض العملاء</span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('users.create') }}" class="nav-link ">
                            <span class="title">اضافة عميل </span>
                        </a>
                    </li>
                </ul>
            </li>
    
            <li class="nav-item {{ strpos(URL::current(), 'cities') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-flag"></i>
                    <span class="title">المدن</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('cities.index') }}" class="nav-link ">
                            <span class="title">عرض المدن </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('cities.create') }}" class="nav-link ">
                            <span class="title"> إضافة مدينة </span>
                        </a>
                    </li>
                </ul>
            </li>
            
            <li class="nav-item {{ strpos(URL::current(), 'regions') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-flag-checkered"></i>
                    <span class="title">المناطق</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('regions.index') }}" class="nav-link ">
                            <span class="title">عرض المناطق </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('regions.create') }}" class="nav-link ">
                            <span class="title"> إضافة منطقة </span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ strpos(URL::current(), 'sections') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-sitemap"></i>
                    <span class="title">الاقسام الرئيسية</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('sections.index') }}" class="nav-link ">
                            <span class="title">عرض الاقسام الرئيسية </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('sections.create') }}" class="nav-link ">
                            <span class="title"> إضافة قسم رئيسى </span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ strpos(URL::current(), 'sub-sections') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-sitemap "></i>
                    <span class="title">الأقسام الفرعية</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('sub-sections.index') }}" class="nav-link ">
                            <span class="title">عرض الأقسام الفرعية </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('sub-sections.create') }}" class="nav-link ">
                            <span class="title"> إضافة قسم </span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ strpos(URL::current(), 'items') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-bullhorn "></i>
                    <span class="title">الإعلانات</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('items.index') }}" class="nav-link ">
                            <span class="title">عرض الإعلانات </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('items.create') }}" class="nav-link ">
                            <span class="title"> إضافة اعلان </span>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item {{ strpos(URL::current(), 'contact') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-envelope"></i>
                    <span class="title">{{ trans('admin.contactUsIndex') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('contactUs.index') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.contactUsShow') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
        
            <li class="nav-item {{ strpos(URL::current(), 'notifications') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-bell"></i>
                    <span class="title">{{ trans('admin.notificationsIndex') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('notifications.create', 'user') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.notificationsUserAdd') }}</span>
                        </a>
                    </li>
                </ul>
            </li>
            
            <li class="nav-item {{ strpos(URL::current(), 'advs') !== false ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="fa fa-bullhorn "></i>
                    <span class="title">الإعلانات الخاصة</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item start ">
                        <a href="{{ route('advs.index') }}" class="nav-link ">
                            <span class="title">عرض الإعلانات </span>
                        </a>
                    </li>
                    <li class="nav-item start ">
                        <a href="{{ route('advs.create') }}" class="nav-link ">
                            <span class="title"> إضافة اعلان </span>
                        </a>
                    </li>
                </ul>
            </li>
            
            <li class="nav-item {{ strpos(URL::current(), 'about') ? 'active' : '' }}">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-globe"></i>
                    <span class="title">{{ trans('admin.aboutTitleShow') }}</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="{{ route('about.create') }}" class="nav-link ">
                            <span class="title">{{ trans('admin.aboutTitleShow') }}</span>
                        </a>
                    </li>
                    
                </ul>
            </li>
        </ul>
    </div>
</div>