bab/routes/web.php
<?php

Route::get('/', [
    'uses' => 'LangingController@index',
    'as' => 'index',
]);

Route::post('/contact', [
    'uses' => 'LangingController@contactUs',
    'as' => 'contactUs.store',
]);

Route::get('/admin-login', [
    'uses' => 'Admin\AuthController@showLoginForm',
    'as' => 'admin.get.login',
]);

Route::post('/admin-login', [
    'uses' => 'Admin\AuthController@login',
    'as' => 'admin.post.login',
]);

Route::post('/logout', [
    'uses' => 'Admin\AuthController@logout',
    'as' => 'logout',
]);

Route::get('/admin-forget-password', [
    'uses' => 'Admin\AuthController@showForgetPasswordForm',
    'as' => 'admin.get-forget-password',
]);

Route::group(['middleware' => 'admin', 'prefix' => 'dashboard', 'namespace' => 'Admin'], function () {
    Route::get('/', [
        'uses' => 'HomeController@dashboard',
        'as' => 'dashboard',
    ]);

    Route::get('/statistics', [
        'uses' => 'HomeController@statistics',
        'as' => 'dashboard-statistics',
    ]);

    Route::resource('admins', 'AdminController', ['except' => ['show', 'destroy']]);

    Route::resource('users', 'UserController', ['except' => ['show','destroy']]);

    Route::resource('cities', 'CitiesController');
    
    Route::resource('regions', 'RegionsController');

    Route::resource('sections', 'SectionsController');

    Route::resource('sub-sections', 'SubsectionController');

    Route::resource('items', 'ItemController', ['except' => ['destroy']]);

    Route::resource('advs', 'AdvsController', ['except' => ['destroy']]);

    Route::resource('about', 'AboutController', ['only' => ['create', 'store']]);

    Route::resource('contactUs', 'ContactUsController', ['only' => ['index', 'show']]);

    Route::get('/change-password', [
        'uses' => 'AdminController@editPassword',
        'as' => 'admins.editPassword',
        ]);

    Route::post('/change-password', [
        'uses' => 'AdminController@changePassword',
        'as' => 'admins.changePassword',
        ]);

    Route::get('/edit-profile', [
        'uses' => 'AdminController@editProfile',
        'as' => 'admins.editProfile',
        ]);

    Route::post('/edit-profile', [
        'uses' => 'AdminController@updateProfile',
        'as' => 'admins.updateProfile',
        ]);

    Route::get('settings/edit', [
        'uses' => 'SettingController@edit',
        'as' => 'settings.edit',
        ]);

    Route::patch('settings/edit', [
        'uses' => 'SettingController@update',
        'as' => 'settings.update',
        ]);

    Route::get('/notifications/{type}', [
        'uses' => 'NotificationController@create',
        'as' => 'notifications.create',
    ]);

    Route::post('/notifications/{type}', [
        'uses' => 'NotificationController@store',
        'as' => 'notifications.store',
    ]);

    Route::post('/users-change-status', [
        'uses' => 'UserController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post('/items-change-status', [
        'uses' => 'ItemController@changeStatus',
        'as' => 'changeStatus',
    ]);

    Route::post( '/cities/change-regions', [
        'uses' => 'CitiesController@changeRegions',
        'as'   => 'cities.changeRegions'
    ] );

    Route::post( '/sections/change-subsections', [
        'uses' => 'ItemController@changeSubsections',
        'as'   => 'sections.changeSubsections'
    ] );

    Route::post('/users-change-account-status', [
        'uses' => 'UserController@changeAccountStatus',
        'as' => 'changeAccountStatus',
    ]);

    Route::get('/users/{user}', [
        'uses' => 'UserController@show',
        'as' => 'users.show',
    ]);

    Route::post('/users/destroy', [
        'uses' => 'UserController@destroy',
        'as' => 'users.destroy',
    ]);

    Route::get('/section-subsections/{section}', [
        'uses' => 'SectionsController@subSections',
        'as' => 'sections.subsections',
    ]);

    Route::post('/contactUs/destroy', [
        'uses' => 'ContactUsController@destroy',
        'as' => 'contactUs.destroy',
    ]);

    Route::post('/contactUs/reply', [
        'uses' => 'ContactUsController@replyMessage',
        'as' => 'contactUs.reply',
    ]);

    Route::post('/cities/destroy', [
        'uses' => 'CitiesController@destroy',
        'as' => 'cities.destroy',
    ]);

    Route::post('/regions/destroy', [
        'uses' => 'regionsController@destroy',
        'as' => 'regions.destroy',
    ]);

    Route::post('/sections/destroy', [
        'uses' => 'sectionsController@destroy',
        'as' => 'sections.destroy',
    ]);

    Route::post('/sub-sections/destroy', [
        'uses' => 'SubsectionsController@destroy',
        'as' => 'subsections.destroy',
    ]);

    Route::post('/items/destroy', [
        'uses' => 'ItemController@destroy',
        'as' => 'items.destroy',
    ]);

    Route::post('/advs/destroy', [
        'uses' => 'AdvsController@destroy',
        'as' => 'advs.destroy',
    ]);

});

bab/app/City.php
<?php

namespace App;

use App\Traits\Translatable;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use Translatable;
    protected $table = 'cities';
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 

    ];
    
     public function regions()
    {
        return $this->hasMany(Region::class);
    }
    
    public function users()
    {
        return $this->hasMany(User::class);
    }
    
    public function Item()
    {
        return $this->belongsTo(Item::class);
    }
}

bab/app/Http/Controllers/Admin/CitiesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class CitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = City::get();

        return view('admin.cities.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    
        return view('admin.cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|max:191',
            'name_en' => 'required|max:191',

        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->route('cities.create')->withErrors($validator)->withInput();
        }

        $created = City::create([
            'name' => $request->name,
        ]);
        $created->createTranslations([
            'name' => $request->get('name_en'),
        ]);
        
        return $created ?
        redirect()->route('cities.create')->with('success', trans('admin.addOk')) :
        redirect()->route('cities.create')->with('warning', trans('admin.addNo'));
    }

    public function edit(City $city)
    {
        return view('admin.cities.edit', compact('city'));
    }

    public function update(Request $request, City $city)
    {
        $rules = [
            'name' => 'required|max:191',
            'name_en' => 'required|max:191',
        ];

        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $city->update($request->all());

        $city->updateTranslations([
            'name' => $request->get('name_en'),
        ]);

        return $city ?
            redirect()->route('cities.index')->with('success', trans('messages.updateTrue')) :
            redirect()->back()->with('warning', trans('messages.updateFalse'));
    }

    public function destroy(Request $request)
    {
        $users = User::where('City_id', $request->id)->count();
        // dd($users);

        if($users > 0){
            return json_encode(['code' => '2', 'message' => 'لا يمكن حذف المدينة للحفاظ على بيانات المستخدمين']);
        }else{
            $city = City::where('id', $request->id)->delete();
            $url = route('cities.index');
    
            return $city
                ? json_encode(['code' => '1', 'url' => $url])
                : json_encode(['code' => '0', 'message' => 'نأسف لحدوث هذا الخطأ, برجاء المحاولة لاحقًا']);
        } 
    }

    public function changeRegions(Request $request) {

        $city_id = $request->city_id;
        $city = City::with('regions')->where('id', $city_id)->first();
        $regions = $city->regions;

        $rows = [];
        foreach ($regions as $region) {
            $rows[] = array(
                "id" => $region->id,
                'text' => $region->name
            );
        }
        return json_encode($rows);
    }

}

bab/resources/views/admin/cities/create.blade.php
@extends('admin.layouts.master')

@section('title')
    إضافة مدينة
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-fileinput.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('cities.index') }}">المدن </a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>إضافة مدينة </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> المدن
        <small>إضافة مدينة جديد</small>
    </h1>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-8">
        <div class="portlet light bordered">
            <div class="portlet-body form">
                {!! Form::open([ 'url' => route('cities.store'), 'class' => 'form-horizontal' ]) !!}
                    <div class="form-group">
                        <label for="name" class="col-lg-3 control-label"> اسم المدينة بالعربية  </label>
                        <div class="col-lg-9">
                            <input type="text" id="name" name="name" class="form-control " placeholder="اسم المدينة بالعربية " required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name_en" class="col-lg-3 control-label"> اسم المدينة بالإنجليزية </label>
                        <div class="col-lg-9">
                            <input type="text" id="name_en" name="name_en" class="form-control " placeholder="اسم المدينة بالإنجليزية  " required>
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-lg-2 col-lg-offset-10">
                                <button type="submit" class="btn green btn-block">حفظ</button>
                            </div>
                        </div>
                    </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/components-select2.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap-fileinput.js') }}"></script>
@endsection

bab/resources/views/admin/cities/edit.blade.php
@extends('admin.layouts.master')

@section('title')
    تعديل المدينة
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/select2-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/bootstrap-fileinput.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('cities.index') }}">المدن</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>تعديل مدينة </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> المدن
        <small>تعديل مدينة </small>
    </h1>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-8">
        <div class="portlet light bordered">
            <div class="portlet-body form">
                {!! Form::model($city, ['method' => 'PATCH', 'url' => route('cities.update', $city->id),'class' => 'form-horizontal']) !!}

                    <div class="form-group">
                        <label for="name" class="col-lg-3 control-label"> اسم المدينة بالعربية  </label>
                        <div class="col-lg-9">
                            <input type="text" id="name" name="name" value="{{ $city->name }}" class="form-control " placeholder="اسم المدينة بالعربية " required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name_en" class="col-lg-3 control-label"> اسم المدينة بالإنجليزية </label>
                        <div class="col-lg-9">
                            {!! Form::text('name_en', isset($city) ? $city->translate('en')->name : null, ['class' => 'form-control', 'required']) !!}
                        </div>
                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-lg-2 col-lg-offset-10">
                                <button type="submit" class="btn green btn-block">حفظ</button>
                            </div>
                        </div>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/select2.full.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/components-select2.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/bootstrap-fileinput.js') }}"></script>
@endsection

bab/resources/views/admin/cities/index.blade.php
@extends('admin.layouts.master')

@section('title')
    المدن
@endsection

@section('styles')
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/datatables.bootstrap-rtl.css') }}">
    <link rel="stylesheet" href="{{ URL::asset('public/admin/css/sweetalert.css') }}">
@endsection

@section('page_header')
    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ route('dashboard') }}">{{ trans('admin.dashboardTitle') }}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{{ route('cities.index') }}">المدن</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>عرض المدن </span>
            </li>
        </ul>
    </div>

    <h1 class="page-title"> عرض المدن
        <small>عرض المدن  </small>
    </h1>
@endsection

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="btn-group">
                                    <a class="btn sbold green" href="{{ route('cities.create') }}"> إضافة جديد
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="btn-group pull-right">
                                    <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown" aria-expanded="false">أدوات
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right">
                                        <li>
                                            <a href="javascript:;">
                                                <i class="fa fa-print"></i> طباعة
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                        <thead>
                        <tr>
                            <th>
                                <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                    <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
                                    <span></span>
                                </label>
                            </th>
                            <th> اسم المدينة بالعربية   </th>
                            <th> اسم المدينة بالإنجليزية  </th>
                            <th> العمليات </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach( $data as $value )
                            <tr class="odd gradeX">
                                <td>
                                    <label class="mt-checkbox mt-checkbox-single mt-checkbox-outline">
                                        <input type="checkbox" class="checkboxes" value="1" />
                                        <span></span>
                                    </label>
                                </td>
                                <td> {{ $value->name }} </td>
                                <td> {{ $value->translate('en')->name }} </td>
                                <td>
                                    <div class="btn-group">
                                        <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false"> العمليات
                                            <i class="fa fa-angle-down"></i>
                                        </button>
                                        <ul class="dropdown-menu pull-left" role="menu">
                                            <li>
                                                <a href="{{ route('cities.edit', $value->id) }}">
                                                    <i class="icon-pencil"></i> تعديل
                                                </a>
                                            </li>
                                            <li>
                                                <a class="delete_data" data="{{ $value->id }}" data_name="{{ $value->name }}">
                                                    <i class="fa fa-times"></i> حذف
                                                </a>
                                            </li>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

@endsection

@section('scripts')
    <script src="{{ URL::asset('public/admin/js/datatable.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/datatables.bootstrap.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/table-datatables-managed.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/sweetalert.min.js') }}"></script>
    <script src="{{ URL::asset('public/admin/js/ui-sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function() {

            var CSRF_TOKEN = $('meta[name="X-CSRF-TOKEN"]').attr('content');

            $('body').on('click', '.delete_data', function() {

                var id = $(this).attr('data');
                var swal_text = ' المدينة  ' + $(this).attr('data_name');
                var swal_title = 'هل أنت متأكد من الحذف ؟';

                swal({
                    title: swal_title,
                    text: swal_text,
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn-warning",
                    confirmButtonText: "تأكيد",
                    cancelButtonText: "إغلاق"
                }, function() {

                    $.ajax({
                        url: "{{ url('/') }}" + "/dashboard/cities/destroy" ,
                        type: "POST",
                        data: {_token: CSRF_TOKEN, 'id' : id},
                    })
                        .done(function(reseived_data) {
                            var parsed_data = $.parseJSON(reseived_data);

                            if(parsed_data.code === '1'){
                                swal({
                                    type: 'success',
                                    title: 'تم الحذف بنجاح',
                                    confirmButtonClass: 'btn-success'
                                }, function() {
                                    window.location.href = parsed_data.url;
                                });
                            }
                            else{
                                swal(
                                    "عملية خاطئة",
                                    parsed_data.message ,
                                    "error"
                                );
                            }
                        });
                });
            });
        });
    </script>
@endsection